---
title: "Analyzing Baseball Team Data Using R Flexdashboards"
author: "Alexander Harriman"
date: "2022-10-10"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggpubr)
library(Lahman)
library(plotly)
library(shiny)
```


```{r, include = FALSE}
#Loading Data

fullTeams <- Lahman::Teams

#Filter out pre-1998 and 2020 seasons

filteredTeams <- fullTeams[fullTeams$yearID >= 1998,]
filteredTeams <- filteredTeams[filteredTeams$yearID != 2020,]

#Removing extraneous columns
cutNames <- c("attendance","BPF","PPF","park","name","DP","SV","SHO","CG","divID","G","Ghome","DivWin","WCWin","LgWin","WSWin","lgID","teamID","franchID","Rank","L","SO","SB","CS","RA","HA","HRA","BBA","SOA","E","teamIDBR","teamIDlahman45","teamIDretro")
filteredTeams <- filteredTeams[,!names(filteredTeams) %in% cutNames]
```


Inputs {.sidebar}
-------

### Histogram Inputs

```{r, echo = FALSE}
#Variable Input
selectInput(inputId = 'Variable', 
            label = 'Select variable to graph', 
            choices = names(filteredTeams))

#Selecting Number of Bins
textInput(inputId = "BinSize", label = "Enter Number of Bins")
```


### Point Plot Inputs

```{r, echo = FALSE}
#Dependent Variable
selectInput(inputId = 'DepVar', 
            label = 'Select dependent variable', 
            choices = names(filteredTeams))

#Independent Variable
selectInput(inputId = 'IndVar', 
            label = 'Select independent variable', 
            choices = names(filteredTeams))
```

### General Inputs

```{r, echo = FALSE}
textInput(inputId = "Color", label = "Enter Color Name or Hexidecimal String", value = "black")
```


Row {data-height=200}
---------------

### Description of Data

```{r, echo = FALSE}
text <- "This database contains pitching, hitting, and fielding statistics for Major League Baseball from 1871 through 2021. It includes data from the two current leagues (American and National), the four other 'major' leagues (American Association, Union Association, Players League, and Federal League), and the National Association of 1871-1875."

renderText(text)
```

Row {.tabset}
---------

### Histogram

```{r, echo = FALSE}
#create histogram from input
renderPlot(ggplot(filteredTeams, 
                  aes_string(x=input$Variable)) + 
  geom_histogram(bins=input$BinSize,
                 fill=input$Color))
```

### Plotting Points by Grouping Variable

```{r, echo = FALSE}
#Create line plots from dependent and independent variables

formulaText <- reactive({paste(input$DepVar, "~", input$IndVar)})

renderPlot(plot(as.formula(formulaText()), pch = 16, data = filteredTeams, main = "Baseball Metric Comparison", xlab = "IndVar", ylab = "DepVar", col = input$Color))

```